learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# template tagging
app_name = 'basic_app'

urlpatterns=[
    path('relative/', views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html',context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-expand-lg navbar-light bg-light'>
      <div class="container-fluid">
        <a class='navbar-brand' href="{% url 'index' %}">BRAND</a>
        <div class="collapse navbar-collapse">
          <ul class='navbar-nav me-auto mb-2 mb-lg-0'>
            <li class='nav-item'><a class='nav-link' href="{% url 'admin:index' %}">ADMIN</a></li>
            <li class='nav-item'><a class='nav-link'href="{% url 'basic_app:other' %}">OTHER</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend -->
      {% endblock %}
    </div>

  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% load my_extras %}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>this is index.html page showing</h2>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:'99' }}</h1>
  {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>this is an example fo template inheritance</h2>
  {% endblock %}

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative_url_templates</h1>
    <a href="{% url 'basic_app:other' %}">the other page</a>
    <a href="{% url 'admin:index' %}">link to admin</a>
    <a href="{% url 'index' %}">link to index</a>

  </body>
</html>